quiz/config/routes.rb
Rails.application.routes.draw do
  resources :answers, :except => [:index, :update, :delete]

  resources :names

  get '/q1' => 'answers#q1'
  get '/admin/checkanswers' => 'answers#checkanswer'
  get '/admin/answers' => 'answers#index'
  get '/register' => 'answers#register'
  get '/en/:name' => 'answers#newentry'
  get '/:name' => 'answers#newentry'
  root 'answers#top'

end

quiz/app/models/name.rb
class Name < ActiveRecord::Base
end

quiz/app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: [:show, :edit, :update, :destroy]

  # GET /names
  # GET /names.json
  def index
    @names = Name.all
  end

  # GET /names/1
  # GET /names/1.json
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(name_params)

    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1
  # PATCH/PUT /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name.destroy
    respond_to do |format|
      format.html { redirect_to names_url, notice: 'Name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def name_params
      params.require(:name).permit(:q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :comment)
    end
end

quiz/app/helpers/names_helper.rb
module NamesHelper
end

quiz/app/views/names/_form.html.erb
<%= form_for(@name) do |f| %>
  <% if @name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
      <% @name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :q1 %><br>
    <%= f.text_field :q1 %>
  </div>
  <div class="field">
    <%= f.label :q2 %><br>
    <%= f.text_field :q2 %>
  </div>
  <div class="field">
    <%= f.label :q3 %><br>
    <%= f.text_field :q3 %>
  </div>
  <div class="field">
    <%= f.label :q4 %><br>
    <%= f.text_field :q4 %>
  </div>
  <div class="field">
    <%= f.label :q5 %><br>
    <%= f.text_field :q5 %>
  </div>
  <div class="field">
    <%= f.label :q6 %><br>
    <%= f.text_field :q6 %>
  </div>
  <div class="field">
    <%= f.label :q7 %><br>
    <%= f.text_field :q7 %>
  </div>
  <div class="field">
    <%= f.label :q8 %><br>
    <%= f.text_field :q8 %>
  </div>
  <div class="field">
    <%= f.label :q9 %><br>
    <%= f.text_field :q9 %>
  </div>
  <div class="field">
    <%= f.label :q10 %><br>
    <%= f.text_field :q10 %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

quiz/app/views/names/edit.html.erb
<h1>Editing name</h1>

<%= render 'form' %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

quiz/app/views/names/index.html.erb
<h1>Listing names</h1>

<table>
  <thead>
    <tr>
      <th>Q1</th>
      <th>Q2</th>
      <th>Q3</th>
      <th>Q4</th>
      <th>Q5</th>
      <th>Q6</th>
      <th>Q7</th>
      <th>Q8</th>
      <th>Q9</th>
      <th>Q10</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @names.each do |name| %>
      <tr>
        <td><%= name.q1 %></td>
        <td><%= name.q2 %></td>
        <td><%= name.q3 %></td>
        <td><%= name.q4 %></td>
        <td><%= name.q5 %></td>
        <td><%= name.q6 %></td>
        <td><%= name.q7 %></td>
        <td><%= name.q8 %></td>
        <td><%= name.q9 %></td>
        <td><%= name.q10 %></td>
        <td><%= name.comment %></td>
        <td><%= link_to 'Show', name %></td>
        <td><%= link_to 'Edit', edit_name_path(name) %></td>
        <td><%= link_to 'Destroy', name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Name', new_name_path %>

quiz/app/views/names/new.html.erb
<h1>New name</h1>

<%= render 'form' %>

<%= link_to 'Back', names_path %>

quiz/app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q1:</strong>
  <%= @name.q1 %>
</p>

<p>
  <strong>Q2:</strong>
  <%= @name.q2 %>
</p>

<p>
  <strong>Q3:</strong>
  <%= @name.q3 %>
</p>

<p>
  <strong>Q4:</strong>
  <%= @name.q4 %>
</p>

<p>
  <strong>Q5:</strong>
  <%= @name.q5 %>
</p>

<p>
  <strong>Q6:</strong>
  <%= @name.q6 %>
</p>

<p>
  <strong>Q7:</strong>
  <%= @name.q7 %>
</p>

<p>
  <strong>Q8:</strong>
  <%= @name.q8 %>
</p>

<p>
  <strong>Q9:</strong>
  <%= @name.q9 %>
</p>

<p>
  <strong>Q10:</strong>
  <%= @name.q10 %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @name.comment %>
</p>

<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>