party/config/routes.rb
Rails.application.routes.draw do
  resources :attends, :except => [:index, :update, :delete]

  get 'q2' => 'attends#q2'
  get 'admin/attends' => 'attends#index'
  get 'invite/:name' => 'attends#invite'
  get 'en/invite/:name' => 'attends#invite_en'
  get 'register' => 'attends#register'
  get 'payment' => 'attends#payment'
  get 'en/payment' => 'attends#payment_en'

  root 'attends#top'

end

party/app/models/attend.rb
class Attend < ActiveRecord::Base
end

party/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

party/app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  before_action :set_attend, only: [:show, :edit, :update, :destroy]
  before_action :set_namehash

  def register
  end

  def invite 
    @attend = Attend.new
    name = params[:name]
    if @namehash.key?(name.to_sym)
    	@attend.name = @namehash[name.to_sym]
    else
	@attend.name = name
    end
 #   render :text => name
  end

  def invite_en
    @english = true
    @attend = Attend.new
    name = params[:name]
    if @namehash.key?(name.to_sym)
    	@attend.name = @namehash[name.to_sym]
    else
	@attend.name = name
    end
  end

  def payment

  end

  def q2

  end

  def payment_en
    @english = true
    render :action => 'payment'
  end

  def top
#	render :text => 'top page'
  end

  # GET /attends
  # GET /attends.json
  def index
    @attends = Attend.all
  end

  # GET /attends/1
  # GET /attends/1.json
  def show
  end

  # GET /attends/new
  def new
    @attend = Attend.new
  end

  # GET /attends/1/edit
  def edit
  end

  # POST /attends
  # POST /attends.json
  def create
    @attend = Attend.new(attend_params)

    respond_to do |format|
      if @attend.save
        format.html { redirect_to action: "register", notice: 'Attend was successfully created.' }
        format.json { render :show, status: :created, location: @attend }
      else
	flash.now[:error] = "submit is unsuccessful."
        format.html { render :invite }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
    #render :html => "register"
  end

  # PATCH/PUT /attends/1
  # PATCH/PUT /attends/1.json
  def update
    respond_to do |format|
      if @attend.update(attend_params)
        format.html { redirect_to @attend, notice: 'Attend was successfully updated.' }
        format.json { render :show, status: :ok, location: @attend }
      else
        format.html { render :edit }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attends/1
  # DELETE /attends/1.json
  def destroy
    @attend.destroy
    respond_to do |format|
      format.html { redirect_to attends_url, notice: 'Attend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attend
      @attend = Attend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attend_params
      params.require(:attend).permit(:name, :attend, :payment, :comment)
    end

    def set_namehash
	@namehash = {
		matsuda_toshihiro: '松田 俊宏',
		etsuda_shogo: '悦田 翔悟',
		yamada_goro: '山田 吾郎',
		sasaki_yusuke: '佐々木 裕介',
		fujiki_tetsuya: '藤木 哲也',
		numaguchi_naoki: '沼口 直紀',
		takado_kazuyuki: '高土 和行',
		hirota_chiharu: '廣田 千春',
		ando_yuki: '安藤 裕紀',
		hayashi_ginji: '林 吟志',
		hayase_hiroki: '早瀬 裕輝',
		murata_kaori: '村田 香織',
		yamaba_yuki: '山羽 佑樹',
		shiratori_keita: '白鳥 啓太',
		nagase_kazuki: '永瀬 一貴',
		hiratsuka_nobuaki: '平塚 信明',
		igarashi_naoto: '五十嵐 直人',
		chiba_daiki: '千葉 大輝',
		konno_kenshiro: '今野 建志郎',
		katagiri_hiroshi: '片桐 浩',
		morimoto_kazushi: '森本 和志',
		yamada_masaki: '山田 聖喜',
		yoshiki_tsuchimoto: '土本 良樹',
		kyono_masatoshi: '教野 雅利',
		sekino_takehisa: '関野 剛永',
		ishii_yasuhiro: '石井 康博',
		ikeda_hiroaki: '池田 浩明',
		kawano_ryohei: '川野 亮平',
		kito_toyokazu: '鬼頭 豊和',
		machida_katsuki: '町田 克樹',
		kuroiwa_junpei: '黒岩 潤平',
		komuro_takeyuki: '小室 健行',
		keiko_nagahama: 'Keiko Nagahama',
		daniel_smadja: 'Daniel Smadja',
		shuji_oya: 'Shuji Oya',
		sayumi_oya: 'Sayumi Oya',
		naoko_oguma: 'Naoko Oguma',
		takashi_ueda: 'Takashi Ueda',
		shin_tanahara: 'Shin Tanahara',
		yutaro_shimizu: 'Yutaro Shimizu',
		kanako_shimizu: 'Kanako Shimizu',
		wada_rina: 'Wada Rina',
		alexandre_plattard: 'Alexandre Plattard',
		aki_nakashima: 'Aki Nakashima',
		miho_iwasaki: 'Miho Iwasaki',
		yumiko_inenaga: 'Yumiko Inenaga',
		ayumi_kojima: 'Ayumi Kojima',
		marina_masuda: 'Marina Masuda',
		alpha_wang: 'Alpha Wang',
		eric_st_louis: 'Eric St-Louis',
		christophe_mathon: 'Christophe Mathon',
		maria_castellanos: 'Maria Castellanos',
		quentin_coupey: 'Quentin Coupey',
		donny_chuc: 'Donny Chuc',
		ozaki_tatsuru: 'Ozaki Tatsuru',
		paul_michael_barraza: 'Paul-Michael Barraza',
		miyake_shinsuke: 'Miyake Shinsuke',
		midori_miyake: 'Midori Miyake',
		kobayashi_kazuhito: 'Kobayashi Kazuhito',
		vincent_leoquet: 'Vincent Leoquet',
		anna_fujimori: 'Anna Fujimori',
		chloe_depigny: 'Chloe Depigny',
		alban_billerey: 'Alban Billerey',
		pierre_charassier: 'Pierre Charassier',
		julien_cocault: 'Julien Cocault',
		jade_cocault: 'Jade Cocault',
		hisako_shimizu: 'Hisako Shimizu',
		junichi_shimizu: 'Junichi Shimizu',
		jose_ferreira: 'Jose Ferreira',
		hiroko_ferreira: 'Hiroko Ferreira',
		hara_mariko: 'Hara Mariko',
		hitachi_yukihiro: 'Hitachi Yukihiro',
		senoo_seiko: 'Senoo Seiko',
		noda_hidetoshi: 'Noda Hidetoshi',
		tobias_krueger: 'Tobias Krueger',
		atsuko_krueger: 'Atsuko Krueger',
		mizue_takeuchi: 'Mizue Takeuchi',
		yachiyo_kato: 'Yachiyo Kato',
		tomoko_yoshino: 'Tomoko Yoshino',
		sato_misaki: 'Sato Misaki',
		chiba_yuji: 'Chiba Yuji',
		kojima_satomi: 'Kojima Satomi',
		chika_yamaguchi: 'Chika Yamaguchi',
		eric_gibault: 'Eric Gibault',
		sekine_makiko: 'Sekine Makiko',
		sayuri_ishii: 'Sayuri Ishii',
		kabashima_seiichiro: '椛島 誠一郎',
		kabashima_erika: '椛島 恵里香',
		takahashi_leona: 'Takahashi Leona',
		todani_hitomi: 'Todani Hitomi'
		}
    end
end

party/app/helpers/application_helper.rb
module ApplicationHelper
end

party/app/helpers/attends_helper.rb
module AttendsHelper
end

party/app/views/attends/_form.html.erb
<%msg_send=(@english == nil) ? "送信する！" : "Send!!" %>
<%msg_attend=(@english == nil) ? "出席可否" : "I will join!" %>
<%msg_confirm=(@english == nil) ? "上記の内容で送信します。よろしいですか？" : "You are about to submit. Are you Okay?" %>

<%= simple_form_for @attend, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name, input_html: {readonly: "readonly" }%>
  <%= f.input :attend, label: msg_attend, checked: ['Yes', true], as: :radio_buttons %>
  <%= f.input :comment %>

  <%= f.button :submit, :class => 'btn-primary', :value => msg_send, data: {confirm: msg_confirm}%>
<!--  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                attends_path, :class => 'btn btn-default' %>
-->
<% end %>

party/app/views/attends/edit.html.erb
<%- model_class = Attend -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

party/app/views/attends/index.html.erb
<%- model_class = Attend -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:attend) %></th>
      <th><%= model_class.human_attribute_name(:payment) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @attends.each do |attend| %>
      <tr>
        <td><%= link_to attend.id, attend_path(attend) %></td>
        <td><%= attend.name %></td>
        <td><%= attend.attend %></td>
        <td><%= attend.payment %></td>
        <td><%= attend.comment %></td>
        <td><%=l attend.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_attend_path(attend), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      attend_path(attend),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_attend_path,
            :class => 'btn btn-primary' %>

party/app/views/attends/invite.html.erb
<%- model_class = Attend -%>
<div class="page-header">
<!--  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1> -->

 <H1>出席回答フォーム</H1>
 <BR/>
<img src="<%= asset_path "img.jpg" %>" width="100%" />

 <h3>Information</h3> 
 <ul>
  <li>日時：4/16(土) 11:00 - 14:30 </li>
  <li>場所：Lemon&Lime Lemon （レモンライム レモン） 
	<ul>
	  <li>〒158-0093 東京都世田谷区上野毛 2-23-10</li>
	  <li><%= link_to 'Google Mapで確認する', 'https://goo.gl/maps/EecSh1wEUx82'  %></li>
	</ul>
  </li>
 </ul>

</div>
<%= render :partial => 'form' %>





<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div>
 <H1>Q1.<H1>
 ここの会場の名前は？
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

party/app/views/attends/invite_en.html.erb
<%- model_class = Attend -%>
<div class="page-header">
<!--  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1> -->

 <H1>Application form</H1>
 <BR/>
<img src="<%= asset_path "img.jpg" %>" width="100%" />

 <h3>Information</h3> 
 <ul>
  <li>Date: Sat 16, Ap 11:00 - 14:30 </li>
  <li>Place: Lemon&Lime Lemon 
	<ul>
	  <li>158-0093 2-23-10, Kaminoge, Setagaya-ku, Tokyo</li>
	  <li><%= link_to 'Jump to Google Map!', 'https://goo.gl/maps/EecSh1wEUx82'  %></li>
	</ul>
  </li>
 </ul>

</div>
<%= render :partial => 'form' %>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div>
 <H1>Q1.<H1>
 What is this studio's name?
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

party/app/views/attends/new.html.erb
<%- model_class = Attend -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

party/app/views/attends/payment.html.erb
<%- model_class = Attend -%>
<%msg_furikomi=(@english == nil) ? "振込先情報" : "Bank Account Information" %>
<%msg_info=(@english == nil) ? "以下の口座のいずれかに振込みをお願いします。" : "Please send money to the account listed below:" %>
<%msg_bank1=(@english == nil) ? "三菱東京UFJ銀行 大和郡山支店(280) 普通 口座番号 4554219 ｻｲﾄｳｱｷﾗ" : "BTMU Bank Yamato Koriyama Branch, Saving Account, Account Number: 4554219, Beneficiary Name: Saito Akira" %>
<%msg_bank2=(@english == nil) ? "新生銀行 本店(400) 普通 口座番号 1432497 ｻｲﾄｳｱｷﾗ" : "Shinsei Bank, Head Office, Saving Account, Account Number: 1432497, Beneficiary Account: Saito Akira" %>
<%msg_bank3=(@english == nil) ? "楽天銀行 オペラ支店(205) 普通 口座番号 1354578 ｻｲﾄｳｱｷﾗ" : "Rakuten Bank, Opera Branch, Saving Account, Account Number:1354578, Beneficiary Name: Saito AKira" %>

<div class="page-header">
<!--  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1> -->
  <H1>振込先情報(Bank Account Information)</H1>
</div>


<div>
  <p>以下の口座のいずれかに振込みをお願いします。</p>
   <ul>
   <li>三菱東京UFJ銀行 大和郡山支店(280) 普通 口座番号 4554219 ｻｲﾄｳｱｷﾗ </li>
   <li>新生銀行 本店(400) 普通 口座番号 1432497 ｻｲﾄｳｱｷﾗ </li>
   <li>楽天銀行 オペラ支店(205) 普通 口座番号 1354578 ｻｲﾄｳｱｷﾗ</li>
 </ul>
</div>
<br>
<div>
  <p>Please send money to the account listed below:</p>
   <ul>
   <li>BTMU Bank Yamato Koriyama Branch, Saving Account, Account Number: 4554219, Beneficiary Name: Saito Akira </li>
   <li>Shinsei Bank, Head Office, Saving Account, Account Number: 1432497, Beneficiary Account: Saito Akira</li>
   <li>Q ten , delete payment character: from url, Account: Saito Akira</li>
   <li>Rakuten Bank, Opera Branch, Saving Account, Account Number:1354578, Beneficiary Name: Saito AKira</li>
 </ul>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<H1> <%= link_to "Q2 はこちら" , :controller => "attends", :action => "q2" %> </H1>
<H1> <%= link_to "Q2 is here " , :controller => "attends", :action => "q2" %> </H1>

party/app/views/attends/payment_en.html.erb
<%- model_class = Attend -%>

Payment page EN

party/app/views/attends/q10.html.erb
<% provide(:title, "BJ") %>

<H1>
Q10.
<pre style="font-size: 22pt"><code>
88 &gt; 77
85 &gt; 84
285 &gt; 164
499 &lt; 99
88 = 79
KK &gt; 99
Q8 = 99
KK2 &lt; 77
QQ = JJ
AA &lt; JJ 

AJ ? KK</code></pre>
</H1>

party/app/views/attends/q2.html.erb
<% provide(:title, "Quiz  --------------------------------> Q2: Where is the groom from ? ") %>
<div class="page-header">

</div>
<div>
 <H1>Q2. このページのどこかに問題があります。</H1>
 <H1>Q2. The question is hidden in this page.</H1>
</div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
 <font color="#FFFFFF">すべて選択した？でもここじゃないよ</font>
 <font color="#FFFFFF">Did you drugged? but answer is not here.</font>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
 <!--
   ソースまで見たあたたはすごい！
　 けどマニアックすぎるのでここに書いていません。。
   You are very nice !! 
   There is no answer here...  
 -->
<br/>
 ここに問題はないです。
 There is no answer here..
<div>
</div>

party/app/views/attends/register.html.erb
<%- model_class = Attend -%>
<div class="page-header">
<!--  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1> -->

</div>
<div>
 <H1>登録を受け付けました。</H1>
 <H1>Thank you for submitting!</H1>
</div>
<div>
 <!--<%= button_tag "Close", type: 'button', onclick: "window.close();", class: "btn btn-success", name:"close", title:"close" %> -->
 <%= button_tag "Close", type: 'button', onclick: "javascript:window.open('about:blank','_self').close();", class: "btn btn-success", name:"close", title:"close" %>
</div>

party/app/views/attends/show.html.erb
<%- model_class = Attend -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @attend.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attend) %>:</strong></dt>
  <dd><%= @attend.attend %></dd>
  <dt><strong><%= model_class.human_attribute_name(:payment) %>:</strong></dt>
  <dd><%= @attend.payment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @attend.comment %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              attends_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_attend_path(@attend), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              attend_path(@attend),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

party/app/views/attends/top.html.erb
q10.html.erb

party/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Akira Aya Saito Wedding Party" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Akira & Aya Saito wedding Party</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
<!--
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
-->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
<!--
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>--><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; a-saitoh 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>