quiz/config/routes.rb
Rails.application.routes.draw do
  resources :answers, :except => [:index, :update, :delete]

  resources :names

  get '/q1' => 'answers#q1'
  get '/admin/checkanswers' => 'answers#checkanswer'
  get '/admin/answers' => 'answers#index'
  get '/register' => 'answers#register'
  get '/en/:name' => 'answers#newentry'
  get '/:name' => 'answers#newentry'
  root 'answers#top'

end

quiz/app/models/answer.rb
class Answer < ActiveRecord::Base
	validates :q1, presence: true 
	validates :q2, presence: true 
	validates :q3, presence: true 
	validates :q4, presence: true 
	validates :q5, presence: true 
	validates :q6, presence: true 
	validates :q7, presence: true 
	validates :q8, presence: true 
	validates :q9, presence: true 
	validates :q10, presence: true 

end

quiz/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_namehash

  helper_method :calcScore
  @test = {}

  def comingsoon
	render :html => "<H1>Coming Soon!!</H1>"
  end

  def q2
  end

  def q10
  end

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  def top
#	render :html => "<H1>Top Page</H1>"
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  def checkanswer
    @answers = []
    @rightanswer = [2,3,3,2,4,  4,1,4,1,1]
    namelist = {}
    @allanswers = Answer.all.order("created_at DESC")
    @allanswers.each{|ans|
	if !namelist.key?(ans.name)
		@answers << ans
		namelist[ans.name] = true
	end
    }
    @answers.sort!{|a,b| 
	if calcScore(b) == calcScore(a)
		a.created_at <=> b.created_at	
        else
		calcScore(b) <=> calcScore(a)
	end
    }

  end

  def newentry
    name = params[:name]
    @answer = Answer.new
    if @namehash.key?(name.to_sym)
	@answer.name = @namehash[name.to_sym]
    else
	@answer.name = name + '(unregistered)'
    end
  end

  def newentries
	rendar :text => "test test"
  end

  # GET /answers/1/edit
  def edit
  end

  def register

  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to action: "register", notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        #format.html { redirect_to action: "newentry", notice: '.' }
	flash.now[:error] = "submit is unsuccessful."
        format.html { render :newentry }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def calcScore(answer)
#	[1..10].each{|i|
#		isCollect()
#	}
	(1..10).inject(0){|sum,i| sum + isCollect(i, answer)}
	#(1..10).inject(0){|sum,i| sum + 1}
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:name, :q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :comment)
    end

    def set_namehash
        @namehash = {
                matsuda_toshihiro: '松田 俊宏',
                etsuda_shogo: '悦田 翔悟',
                yamada_goro: '山田 吾郎',
                sasaki_yusuke: '佐々木 裕介',
                fujiki_tetsuya: '藤木 哲也',
                numaguchi_naoki: '沼口 直紀',
                takado_kazuyuki: '高土 和行',
                hirota_chiharu: '廣田 千春',
                ando_yuki: '安藤 裕紀',
                hayashi_ginji: '林 吟志',
                hayase_hiroki: '早瀬 裕輝',
                murata_kaori: '村田 香織',
                yamaba_yuki: '山羽 佑樹',
                shiratori_keita: '白鳥 啓太',
                nagase_kazuki: '永瀬 一貴',
                hiratsuka_nobuaki: '平塚 信明',
                igarashi_naoto: '五十嵐 直人',
                chiba_daiki: '千葉 大輝',
                konno_kenshiro: '今野 建志郎',
                katagiri_hiroshi: '片桐 浩',
                morimoto_kazushi: '森本 和志',
                yamada_masaki: '山田 聖喜',
                yoshiki_tsuchimoto: '土本 良樹',
                kyono_masatoshi: '教野 雅利',
                sekino_takehisa: '関野 剛永',
                ishii_yasuhiro: '石井 康博',
                ikeda_hiroaki: '池田 浩明',
                kawano_ryohei: '川野 亮平',
                kito_toyokazu: '鬼頭 豊和',
                machida_katsuki: '町田 克樹',
                kuroiwa_junpei: '黒岩 潤平',
                komuro_takeyuki: '小室 健行',
                keiko_nagahama: 'Keiko Nagahama',
                daniel_smadja: 'Daniel Smadja',
                shuji_oya: 'Shuji Oya',
                sayumi_oya: 'Sayumi Oya',
                naoko_oguma: 'Naoko Oguma',
                takashi_ueda: 'Takashi Ueda',
                shin_tanahara: 'Shin Tanahara',
                yutaro_shimizu: 'Yutaro Shimizu',
                kanako_shimizu: 'Kanako Shimizu',
                wada_rina: 'Wada Rina',
                alexandre_plattard: 'Alexandre Plattard',
                aki_nakashima: 'Aki Nakashima',
                miho_iwasaki: 'Miho Iwasaki',
                yumiko_inenaga: 'Yumiko Inenaga',
                ayumi_kojima: 'Ayumi Kojima',
                marina_masuda: 'Marina Masuda',
                alpha_wang: 'Alpha Wang',
                eric_st_louis: 'Eric St-Louis',
                christophe_mathon: 'Christophe Mathon',
                maria_castellanos: 'Maria Castellanos',
                quentin_coupey: 'Quentin Coupey',
                donny_chuc: 'Donny Chuc',
                ozaki_tatsuru: 'Ozaki Tatsuru',
                paul_michael_barraza: 'Paul-Michael Barraza',
                miyake_shinsuke: 'Miyake Shinsuke',
                midori_miyake: 'Midori Miyake',
                kobayashi_kazuhito: 'Kobayashi Kazuhito',
                vincent_leoquet: 'Vincent Leoquet',
                anna_fujimori: 'Anna Fujimori',
                chloe_depigny: 'Chloe Depigny',
                alban_billerey: 'Alban Billerey',
                pierre_charassier: 'Pierre Charassier',
                julien_cocault: 'Julien Cocault',
                jade_cocault: 'Jade Cocault',
                hisako_shimizu: 'Hisako Shimizu',
                junichi_shimizu: 'Junichi Shimizu',
                jose_ferreira: 'Jose Ferreira',
                hiroko_ferreira: 'Hiroko Ferreira',
                hara_mariko: 'Hara Mariko',
                hitachi_yukihiro: 'Hitachi Yukihiro',
                senoo_seiko: 'Senoo Seiko',
                noda_hidetoshi: 'Noda Hidetoshi',
                tobias_krueger: 'Tobias Krueger',
                atsuko_krueger: 'Atsuko Krueger',
                mizue_takeuchi: 'Mizue Takeuchi',
                yachiyo_kato: 'Yachiyo Kato',
                tomoko_yoshino: 'Tomoko Yoshino',
                sato_misaki: 'Sato Misaki',
                chiba_yuji: 'Chiba Yuji',
                kojima_satomi: 'Kojima_Satomi',
                chika_yamaguchi: 'Chika Yamaguchi',
                eric_gibault: 'Eric Gibault',
                sekine_makiko: 'Sekine Makiko',
                sayuri_ishii: 'Sayuri Ishii',
                kabashima_seiichiro: '椛島 誠一郎',
                kabashima_erika: '椛島 恵里香',
		takahashi_leona: 'Takahashi Leona',
		todani_hitomi: 'Todani Hitomi'
                }
    end

   def isCollect(num, answer)
	case num
	when 1 then
		answer.q1.to_i == @rightanswer[1 - 1] ? 1 : 0
	when 2 then
		answer.q2.to_i == @rightanswer[2 - 1] ? 1 : 0
	when 3 then
		answer.q3.to_i == @rightanswer[3 - 1] ? 1 : 0
	when 4 then
		answer.q4.to_i == @rightanswer[4 - 1] ? 1 : 0
	when 5 then
		answer.q5.to_i == @rightanswer[5 - 1] ? 1 : 0
	when 6 then
		answer.q6.to_i == @rightanswer[6 - 1] ? 1 : 0
	when 7 then
		answer.q7.to_i == @rightanswer[7 - 1] ? 1 : 0
	when 8 then
		answer.q8.to_i == @rightanswer[8 - 1] ? 1 : 0
	when 9 then
		answer.q9.to_i == @rightanswer[9 - 1] ? 1 : 0
	when 10 then
		answer.q10.to_i == @rightanswer[10 - 1] ? 1 : 0
        else
 
  	end
   end
end

quiz/app/helpers/answers_helper.rb
module AnswersHelper
end

quiz/app/views/answers/_form.html.erb
<%= simple_form_for @answer, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name, input_html: {readonly: "readonly"} %>
  <%= f.input :q1 , required: true, collection: [["1: Orange", 1],["2: Lemon & Lime", 2],["3: Apple", 3],["4: Watermelon", 4]]%>
  <%= f.input :q2 , required: true, collection: [["1: Kyoto", 1],["2: Tokyo", 2],["3: Nara", 3],["4: Kanagawa", 4]]%>
  <%= f.input :q3 , required: true, collection: [["1: Harvard University", 1],["2: Osaka University", 2],["3: Pierre and Marie Curie University ", 3],["4: Paris Dauphine", 4]]%>
  <%= f.input :q4 , required: true, collection: [["1: Panda", 1],["2: Owl", 2],["3: Cat", 3],["4: Camel", 4]]%>
  <%= f.input :q5 , required: true, collection: [["1: 11", 1],["2: 12", 2],["3: 13", 3],["4: 14", 4]]%>
  <%= f.input :q6 , required: true, collection: [["1: 0", 1],["2: 1", 2],["3: 2", 3],["4: 5", 4]]%>
  <%= f.input :q7 , required: true, collection: [["1: AS", 1],["2: TO", 2],["3: THE", 3],["4: HOGE", 4]]%>
  <%= f.input :q8 , required: true, collection: [["1: Box", 1],["2: Wood", 2],["3: Party", 3],["4: Wedding", 4]]%>
  <%= f.input :q9 , required: true, collection: [["1: Panda", 1],["2: Owl", 2],["3: Cat", 3],["4: Camel", 4]]%>
  <%= f.input :q10 , required: true, collection: [["1: > ", 1],["2: < ", 2],["3: = ", 3],["4: ≒ ", 4]]%>
  <%= f.input :comment %>

  <%= f.button :submit, :class => 'btn-primary', :value => '送信する！', data: {confirm: "上記の内容で送信します。よろしいですか？"}%>
<!--  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                answers_path, :class => 'btn btn-default' %>
-->
<% end %>

quiz/app/views/answers/checkanswer.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:q1) %></th>
      <th><%= model_class.human_attribute_name(:q2) %></th>
      <th><%= model_class.human_attribute_name(:q3) %></th>
      <th><%= model_class.human_attribute_name(:q4) %></th>
      <th><%= model_class.human_attribute_name(:q5) %></th>
      <th><%= model_class.human_attribute_name(:q6) %></th>
      <th><%= model_class.human_attribute_name(:q7) %></th>
      <th><%= model_class.human_attribute_name(:q8) %></th>
      <th><%= model_class.human_attribute_name(:q9) %></th>
      <th><%= model_class.human_attribute_name(:q10) %></th>
      <th>Score</th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to answer.id, answer_path(answer) %></td>
        <td><%= answer.name %></td>
        <td><%= answer.q1 %></td>
        <td><%= answer.q2 %></td>
        <td><%= answer.q3 %></td>
        <td><%= answer.q4 %></td>
        <td><%= answer.q5 %></td>
        <td><%= answer.q6 %></td>
        <td><%= answer.q7 %></td>
        <td><%= answer.q8 %></td>
        <td><%= answer.q9 %></td>
        <td><%= answer.q10 %></td>
        <td><%= calcScore(answer) %></td>
        <td><%= answer.comment %></td>
        <td><%=l answer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_answer_path(answer), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      answer_path(answer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_answer_path,
            :class => 'btn btn-primary' %>

quiz/app/views/answers/edit.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

quiz/app/views/answers/index.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:q1) %></th>
      <th><%= model_class.human_attribute_name(:q2) %></th>
      <th><%= model_class.human_attribute_name(:q3) %></th>
      <th><%= model_class.human_attribute_name(:q4) %></th>
      <th><%= model_class.human_attribute_name(:q5) %></th>
      <th><%= model_class.human_attribute_name(:q6) %></th>
      <th><%= model_class.human_attribute_name(:q7) %></th>
      <th><%= model_class.human_attribute_name(:q8) %></th>
      <th><%= model_class.human_attribute_name(:q9) %></th>
      <th><%= model_class.human_attribute_name(:q10) %></th>
      <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to answer.id, answer_path(answer) %></td>
        <td><%= answer.name %></td>
        <td><%= answer.q1 %></td>
        <td><%= answer.q2 %></td>
        <td><%= answer.q3 %></td>
        <td><%= answer.q4 %></td>
        <td><%= answer.q5 %></td>
        <td><%= answer.q6 %></td>
        <td><%= answer.q7 %></td>
        <td><%= answer.q8 %></td>
        <td><%= answer.q9 %></td>
        <td><%= answer.q10 %></td>
        <td><%= answer.comment %></td>
        <td><%=l answer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_answer_path(answer), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      answer_path(answer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_answer_path,
            :class => 'btn btn-primary' %>

quiz/app/views/answers/new.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%=  render :partial => 'form' %> 

quiz/app/views/answers/newentry.html.erb
<%- model_class = Answer -%>
<div class="page-header">
<!--  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1> -->
<h1>回答フォーム</h1>
</div>
<%=  render :partial => 'form' %> 

quiz/app/views/answers/q10.html.erb
<HTML><HEAD><TITLE>TOP PAGE </TITLE></HEAD>

<BODY>
<H1>
Q10.
<pre style="font-size: 22pt"><code>
88 &gt; 77
85 &gt; 84
285 &gt; 164
499 &lt; 99
88 = 79
KK &gt; 99
Q8 = 99
KK2 &lt; 77
AA &lt; JJ 

AJ ? KK</code></pre>
</H1>
</BODY>
</HTML>

quiz/app/views/answers/q2.html.erb
<% provide(:title, "Quiz  ------------------------------> Answer: famous programming language ") %>
<%- model_class = Answer -%>
<div class="page-header">
<!--  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1> -->

</div>
<div>
 <H1>Q2. このページのどこかに答えがあります。</H1>
 <H1>Q2. The answer is hidden in this page.</H1>
</div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
 <font color="#FFFFFF">すべて選択した？でもここじゃないよ</font>
 <font color="#FFFFFF">Did you drugged? but answer is not here.</font>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
 <!--
   答え：ソースまで見たあたたはすごい！
　 けどマニアックすぎるのでここに答えは書いていません。。
   There is no answer here...  
 -->
<br/>
 ここに答えはないです。
 There is no answer here..
<div>
</div>

quiz/app/views/answers/register.html.erb
<%- model_class = Answer -%>
<div class="page-header">
<!--  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1> -->

</div>
<div>
 <H1>投稿を受け付けました。</H1>
 <H1>Thank you for submitting!</H1>
</div>
<div>
 <!--<%= button_tag "Close", type: 'button', onclick: "window.close();", class: "btn btn-success", name:"close", title:"close" %> -->
 <%= button_tag "Close", type: 'button', onclick: "javascript:window.open('about:blank','_self').close();", class: "btn btn-success", name:"close", title:"close" %>
</div>

quiz/app/views/answers/show.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @answer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q1) %>:</strong></dt>
  <dd><%= @answer.q1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q2) %>:</strong></dt>
  <dd><%= @answer.q2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q3) %>:</strong></dt>
  <dd><%= @answer.q3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q4) %>:</strong></dt>
  <dd><%= @answer.q4 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q5) %>:</strong></dt>
  <dd><%= @answer.q5 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q6) %>:</strong></dt>
  <dd><%= @answer.q6 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q7) %>:</strong></dt>
  <dd><%= @answer.q7 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q8) %>:</strong></dt>
  <dd><%= @answer.q8 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q9) %>:</strong></dt>
  <dd><%= @answer.q9 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:q10) %>:</strong></dt>
  <dd><%= @answer.q10 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comment) %>:</strong></dt>
  <dd><%= @answer.comment %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              answers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_answer_path(@answer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              answer_path(@answer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

quiz/app/views/answers/top.html.erb
<HTML><HEAD><TITLE>TOP PAGE</TITLE></HEAD><BODY><H1>TOP PAGE</H1></BODY></HTML>